version: "3.8"

services:
  goldenstack:
    container_name: goldenstack
    image: 764525110978.dkr.ecr.us-west-2.amazonaws.com/goldenstack:1
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG-}
      - SERVICES=dynamodb,s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
