graph LR
A(fa:fa-server warehouse.ai)
B(fa:fa-opencart web service)
C{fa:fa-database No-SQL Database}
D[fa:fa-laptop browser]

B --> |"get assets from CDN"| D
C --> |"fetch metadata"| A
A --> |"get CDN metadata - wrhs.ai-client"| B
