graph LR
A>BUILD]
B(fa:fa-toolbox carpenterd)
C{fa:fa-broadcast-tower NSQ}
D(fa:fa-spinner carpenterd-worker)
E{fa:fa-box-open S3 compatible CDN}
F{fa:fa-database No-SQL Database}

A -.-> |"<small>{ NODE_ENV: env, LOCALE: locale }</small>"| B
B --> |"enqueue build"|C
D --> |"subscribe"| C
D --> |"store build output"| E
D --> |"build metadata"| F

style A fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
