graph LR
A(npm dist-tag add)
B(fa:fa-server warehouse.ai)
C{fa:fa-database No-SQL Database}
D{fa:fa-database Artifactory}
E>BUILD]

B -.-> E
B --> |"update module {version@env}"| C
D --> |"fetch @version tarball"| B
A -->|"module@version env"| B

style E fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
