graph LR
A(npm dist-tag add)
B(fa:fa-server warehouse.ai)
C{fa:fa-database npm-like registry}
D>BUILD]

B -.-> |"{NODE_ENV=env, ...metadata}"| D
C --> |"fetch @version tarball"| B
B --> |"store dist-tag"| C
A --> |"module@version env"| B

style D fill:#ccf,stroke:#f66,stroke-width:2px,stroke-dasharray: 5, 5
