graph TD
C -->|enqueue build|D{NSQ}
E(<br>carpenterd-worker<br><br>) --> |subscribe| D
B --> C(<br>carpenterd<br><br>)
A(npm publish) -->|publish tarball| B(<br>warehouse.ai<br><br>)
E --> |write to bucket| F{S3 compatibile CDN}
