name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LOCALSTACK_URL: http://localstack:4566
    services:
      localstack:
        image: localstack/localstack:0.11.6
        ports:
          - 4566:4566
          - 9999:9999
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
