name: Test

on: 
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,s3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci

      - name: Initialize Localstack
        run: npm run init-localstack
      
      - name: Run Tests
        run: npm test