name: Test

on: 
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:1.4.0
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,s3
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci

      - name: Initialize Localstack
        run: npm run init-localstack
      
      - name: Run Tests
        run: npm test